version: "3.8"

services:
  web:
    image: parket-suprimentos:latest
    networks:
      - network_public
    deploy:
      replicas: 1
      restart_policy: { condition: any }
      update_config: { parallelism: 1, delay: 5s, order: start-first }
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=network_public"
        - "traefik.constraint-label=network_public"

        - "traefik.http.routers.suprimentos.rule=Host(`suprimentos.parket.works`)"
        - "traefik.http.routers.suprimentos.entrypoints=websecure"
        - "traefik.http.routers.suprimentos.tls=true"
        - "traefik.http.routers.suprimentos.tls.certresolver=letsencryptresolver"
        - "traefik.http.routers.suprimentos.service=suprimentos"

        - "traefik.http.routers.suprimentos-http.rule=Host(`suprimentos.parket.works`)"
        - "traefik.http.routers.suprimentos-http.entrypoints=web"
        - "traefik.http.routers.suprimentos-http.middlewares=suprimentos-https-redirect"
        - "traefik.http.routers.suprimentos-http.service=suprimentos"

        - "traefik.http.services.suprimentos.loadbalancer.server.port=80"

        - "traefik.http.middlewares.suprimentos-https-redirect.redirectscheme.scheme=https"
        - "traefik.http.middlewares.suprimentos-https-redirect.redirectscheme.permanent=true"

networks:
  network_public:
    external: true
