version: "3.8"

services:
  web:
    image: parket-insta-web:latest
    networks:
      - network_public
    deploy:
      resources:
        limits:
          memory: 96M
      mode: replicated
      replicas: 1
      restart_policy: { condition: on-failure }
      update_config: { parallelism: 1, order: start-first, failure_action: rollback }
      labels:
        - traefik.enable=true
        - traefik.docker.network=network_public
        - traefik.http.routers.parket-insta-http.rule=Host(`insta.parket.works`)
        - traefik.http.routers.parket-insta-http.entrypoints=web
        - traefik.http.routers.parket-insta-http.middlewares=https-redirect
        - traefik.http.routers.parket-insta.rule=Host(`insta.parket.works`)
        - traefik.http.routers.parket-insta.entrypoints=websecure
        - traefik.http.routers.parket-insta.tls=true
        - traefik.http.routers.parket-insta.tls.certresolver=letsencryptresolver
        - traefik.http.services.parket-insta.loadbalancer.server.port=80

networks:
  network_public:
    external: true
