FROM parket-dashboard:golden
COPY default.conf /etc/nginx/conf.d/default.conf
COPY orcamento-simulador-tab-MARCFIX27.js /usr/share/nginx/html/assets/orcamento-simulador-tab-MARCFIX27.js
COPY index.html /usr/share/nginx/html/index.html
COPY dept-layout-v2-BtZpIBbo.js /usr/share/nginx/html/assets/dept-layout-v2-BtZpIBbo.js
COPY dept-orcamento-CCurE3y-.js /usr/share/nginx/html/assets/dept-orcamento-CCurE3y-.js
COPY index-DZtetJYP.js /usr/share/nginx/html/assets/index-DZtetJYP.js
COPY index-v2-DZtetJYP.js /usr/share/nginx/html/assets/index-v2-DZtetJYP.js
