FROM parket-dashboard:golden
COPY orcamento-simulador-tab-MARCFIX2.js /usr/share/nginx/html/assets/orcamento-simulador-tab-MARCFIX2.js
COPY AreaChart-DpkIHS8Q.js /usr/share/nginx/html/assets/AreaChart-DpkIHS8Q.js
COPY nginx/default.conf /etc/nginx/conf.d/default.conf
