FROM parket-dashboard:golden
COPY index.html /usr/share/nginx/html/index.html
COPY proposta-publica-page-V12FIX.js /usr/share/nginx/html/assets/proposta-publica-page-V12FIX.js
COPY proposta-publica-page-V13FIX.js /usr/share/nginx/html/assets/proposta-publica-page-V13FIX.js
COPY propostaGenerator-PGSTRUCT35.js /usr/share/nginx/html/assets/propostaGenerator-PGSTRUCT35.js
