FROM parket-dashboard:golden
COPY default.conf /etc/nginx/conf.d/default.conf
COPY orcamento-simulador-tab-MARCFIX24.js /usr/share/nginx/html/assets/orcamento-simulador-tab-MARCFIX24.js
COPY propostaGenerator-PGSTRUCT17.js /usr/share/nginx/html/assets/propostaGenerator-PGSTRUCT17.js
