import { useState, useEffect, useCallback } from "react";
import { supabase } from "../lib/supabase";

export interface AlertaComment {
  id: string;
  user: string;
  message: string;
  timestamp: string;
}

export interface Alerta {
  id: string;
  severity: "critical" | "warning" | "info";
  rule: string;
  message: string;
  dept: string;
  obra_id?: string;
  auto_generated: boolean;
  resolved: boolean;
  resolved_at?: string;
  resolved_by?: string;
  // Campos dinâmicos
  description?: string;
  status: "pendente" | "em-analise" | "finalizado";
  comments?: AlertaComment[];
  created_at: string;
  updated_at: string;
}

export function toSmartAlert(a: Alerta) {
  return {
    id: a.id,
    severity: a.severity,
    rule: a.rule,
    message: a.message,
    dept: a.dept,
    obra: a.obra_id ?? undefined,
    autoGenerated: a.auto_generated,
    timestamp: new Date(a.created_at).toLocaleString("pt-BR", {
      day: "2-digit", month: "2-digit", hour: "2-digit", minute: "2-digit",
    }),
  };
}

export function useAlertas() {
  const [alertas, setAlertas] = useState<Alerta[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  const fetchAlertas = useCallback(async () => {
    setLoading(true);
    setError(null);
    const { data, error: err } = await supabase
      .from("alertas")
      .select("*")
      .eq("resolved", false)
      .order("severity", { ascending: true })
      .order("created_at", { ascending: false });

    if (err) setError(err.message);
    else setAlertas((data ?? []).map(a => ({ ...a, status: a.status ?? "pendente", comments: a.comments ?? [] })));
    setLoading(false);
  }, []);

  useEffect(() => {
    fetchAlertas();
    const channel = supabase
      .channel("alertas_changes")
      .on("postgres_changes", { event: "*", schema: "public", table: "alertas" }, () => fetchAlertas())
      .subscribe();
    return () => { supabase.removeChannel(channel); };
  }, [fetchAlertas]);

  const getAlertasByDept = useCallback((dept: string) =>
    alertas.filter(a => a.dept === dept), [alertas]);

  const getBySeverity = useCallback((severity: Alerta["severity"]) =>
    alertas.filter(a => a.severity === severity), [alertas]);

  /* ─── Atualizar campos do alerta ─── */
  const updateAlerta = useCallback(async (id: string, fields: Partial<Pick<Alerta, "description" | "status" | "comments" | "rule" | "message">>) => {
    const { error: err } = await supabase.from("alertas").update(fields).eq("id", id);
    if (err) throw new Error(err.message);
    setAlertas(prev => prev.map(a => a.id === id ? { ...a, ...fields } : a));
  }, []);

  /* ─── Adicionar comentário ─── */
  const addComment = useCallback(async (id: string, user: string, message: string) => {
    const alerta = alertas.find(a => a.id === id);
    const current: AlertaComment[] = alerta?.comments ?? [];
    const comment: AlertaComment = {
      id: crypto.randomUUID(),
      user,
      message,
      timestamp: new Date().toISOString(),
    };
    const updated = [...current, comment];
    const { error: err } = await supabase.from("alertas").update({ comments: updated }).eq("id", id);
    if (err) throw new Error(err.message);
    setAlertas(prev => prev.map(a => a.id === id ? { ...a, comments: updated } : a));
  }, [alertas]);

  /* ─── Resolver alerta ─── */
  const resolveAlerta = useCallback(async (id: string, resolvedBy?: string) => {
    const { error: err } = await supabase
      .from("alertas")
      .update({ resolved: true, status: "finalizado", resolved_at: new Date().toISOString(), resolved_by: resolvedBy ?? null })
      .eq("id", id);
    if (err) throw new Error(err.message);
    setAlertas(prev => prev.filter(a => a.id !== id));
  }, []);

  /* ─── Criar alerta ─── */
  const createAlerta = useCallback(async (alerta: Pick<Alerta, "severity" | "rule" | "message" | "dept"> & { obra_id?: string; description?: string }) => {
    const { data, error: err } = await supabase
      .from("alertas")
      .insert({ ...alerta, auto_generated: false, status: "pendente", comments: [] })
      .select()
      .single();
    if (err) throw new Error(err.message);
    const novo = { ...(data as Alerta), status: (data as any).status ?? "pendente", comments: [] };
    setAlertas(prev => [novo, ...prev]);
    return novo;
  }, []);

  const smartAlerts = alertas.map(toSmartAlert);

  return {
    alertas,
    smartAlerts,
    loading,
    error,
    refetch: fetchAlertas,
    getAlertasByDept,
    getBySeverity,
    updateAlerta,
    addComment,
    resolveAlerta,
    createAlerta,
    criticalCount: alertas.filter(a => a.severity === "critical").length,
    warningCount: alertas.filter(a => a.severity === "warning").length,
    infoCount: alertas.filter(a => a.severity === "info").length,
  };
}
