server {
  listen 80 default_server;
  server_name _;

  gzip on;
  gzip_types text/css application/javascript application/json text/plain;

  location /b/ {
    root /usr/share/nginx/html;
    try_files $uri /b/index.html;
    add_header Cache-Control "no-cache, must-revalidate, max-age=0";
  }

  location = /healthz {
    add_header Content-Type text/plain;
    return 200 "ok\n";
  }

  location / {
    return 404;
  }
}
