-- ================================================================
-- Parket Dashboard — Seed: todos os cards estáticos do Kanban
-- Execute APÓS as migrations 001, 002 e 003
-- ================================================================

INSERT INTO public.kanban_cards (dept_id, column_id, title, subtitle, obra, responsavel, sla, sla_status, value, priority, tags, progress, gate)
VALUES

-- ═══ COMERCIAL ═══
('comercial','prospeccao','Silvia Alarico Neves','ID 1807 — 3 Portas Pivotantes · Madeira pendente','Silvia Alarico Neves','BDR','D+1','warning','R$ 85k',NULL,ARRAY['SP'],NULL,NULL),
('comercial','prospeccao','Robinho e Mariana','ID 2254 — Novo Rumo — 5 Portas','Robinho e Mariana','BDR','D+2','ok','R$ 65k',NULL,ARRAY['SP'],NULL,NULL),
('comercial','qualificacao','GIC Patrimonial','ID 2342 — Pendente definicao fechaduras','GIC Patrimonial','Closer','D+5','expired','R$ 180k',NULL,ARRAY['SP','impedimento'],NULL,NULL),
('comercial','qualificacao','Mohmed Nazir','ID 1629 — Cortineiro Clodoaldo — novo contrato','Mohmed Nazir','Closer','D+3','warning','R$ 45k',NULL,ARRAY['SP'],NULL,NULL),
('comercial','proposta','Claudio Mohn Franca','ID 2272 — 48.6m2 Painel + 45m2 Brises + 46 Portas · Peroba Laca','Claudio Mohn Franca','Closer','D+5','ok','R$ 420k','alta',NULL,NULL,NULL),
('comercial','negociacao','Trocha Family — Solarius','ID 1312 — 726m2 Painel + 130m Brise + 27 Portas · Internacional','Trocha Family','Closer','D+10','ok','R$ 850k','alta',ARRAY['Alemanha/Fazenda','internacional'],NULL,NULL),
('comercial','fechamento','Jorbel — Paraguay','Piso-Forro e Deck · Contrato internacional assinado','Jorbel','Closer','D+2','ok','R$ 420k',NULL,ARRAY['PY'],NULL,NULL),
('comercial','fechamento','Felipe Almeida — Baronesa','Pergolado + Forro Projeto · Contrato fechado','Felipe Almeida','Closer','OK','ok','R$ 340k',NULL,ARRAY['Baronesa'],NULL,NULL),

-- ═══ PROJETOS ═══
('projetos','briefing','Claudio Mohn Franca','ID 2272 — 48.6m2 Painel + 45m2 Brises + 46 Portas Peroba Laca','Claudio Mohn Franca','Thainara','5d','ok',NULL,'alta',ARRAY['marc','SP'],NULL,NULL),
('projetos','briefing','Silvia Alarico Neves','ID 1807 — 3 Portas Pivotantes · Madeira pendente definicao','Silvia Alarico Neves','Thainara','3d','warning',NULL,NULL,ARRAY['marc'],NULL,NULL),
('projetos','desenvolvimento','Rafaela Di Mais','ID 2347 — 1 Porta Pivotante + 1 Bancada + 1 Portico','Rafaela Di Mais','Thainara','3d','ok',NULL,NULL,ARRAY['marc','SP'],NULL,NULL),
('projetos','desenvolvimento','Luana Bastos de Oliveira','ID 1341 — 12 Portas + 23m3 Painel Tauari + Cortineiro + Bancos','Luana Bastos','Thainara','5d','ok',NULL,NULL,ARRAY['marc','RJ'],NULL,NULL),
('projetos','revisao','Eduardo Grunebaum','ID 2240 — 4.14 Cortineiro + 7 Mulsanca · BLOQUEADO: cliente indisponivel','Eduardo Grunebaum','Thainara','VENCIDO','expired',NULL,'alta',ARRAY['bloqueado'],NULL,NULL),
('projetos','revisao','Pedro Campos','ID 2278 — Obra paralisada — prioridade Priscila Dear','Pedro Campos','Thainara','VENCIDO','expired',NULL,NULL,ARRAY['paralisado','BSB'],NULL,NULL),
('projetos','aprovado','Ana Cristina Garcia','ID 2307 — 10 Portas Pivotantes Nogueira · Projeto OK (18/11)','Ana Cristina Garcia','Thainara','OK','ok',NULL,NULL,ARRAY['marc'],NULL,1),
('projetos','aprovado','Bernardo Coutinho','ID 1125 — 10 Portas Pivotantes Carvalho Europeu','Bernardo Coutinho','Thainara','OK','ok',NULL,NULL,ARRAY['marc','RJ'],NULL,1),
('projetos','aprovado','Cibele Hasmann','ID 2242/2341 — Marcenaria Formica','Cibele Hasmann','Thainara','OK','ok',NULL,NULL,ARRAY['marc'],NULL,1),
('projetos','bom','Alexandre Assumpcao','ID 1095 — 4 Portas Carvalho Europeu Natural · BOM pronta','Alexandre Assumpcao','Thainara','OK','ok',NULL,NULL,ARRAY['marc'],NULL,NULL),
('projetos','bom','Henrique de Menezes','ID 221 — Paineis Hall + Porta + Forro Carvalho · BOM v2','Henrique de Menezes','Thainara','OK','ok',NULL,NULL,ARRAY['marc'],NULL,NULL),

-- ═══ COMPRAS ═══
('compras','requisicao','Claudio Mohn Franca','ID 2272 — Peroba Laca: 48.6m2 Painel + 45m2 Brises + 46 Portas','Claudio Mohn','Ronaldo','5d','ok','R$ 180k','alta',ARRAY['marc','volume alto'],NULL,NULL),
('compras','requisicao','Trocha Family — Solarius','ID 1312 — Cabreuva: 726m2 Painel + 130m Brise + 27 Portas','Trocha Family','Ronaldo','3d','warning','R$ 320k','alta',ARRAY['internacional','urgente'],NULL,NULL),
('compras','cotacao','Luana Bastos de Oliveira','ID 1341 — Tauari: 12 Portas + 23m3 Painel + Cortineiro + Bancos','Luana Bastos','Ronaldo','3d','ok','R$ 95k',NULL,ARRAY['marc','RJ'],NULL,NULL),
('compras','cotacao','Robinho e Mariana','ID 2254 — 5 Portas · Cotando madeira','Robinho e Mariana','Ronaldo','2d','ok','R$ 22k',NULL,NULL,NULL,NULL),
('compras','po','Bernardo Coutinho','ID 1125 — PO Carvalho Europeu: 10 Portas Pivotantes','Bernardo Coutinho','Ronaldo','5d','ok','R$ 67k',NULL,NULL,NULL,NULL),
('compras','po','Amanda Rosales','ID 2310 — Carvalho Mont Blanc: Lamina Nevado','Amanda Rosales','Ronaldo','4d','ok','R$ 38k',NULL,NULL,NULL,NULL),
('compras','aguardando','Henrique de Menezes','ID 221 — Carvalho Europeu: Paineis Hall + Porta + Forro','Henrique de Menezes','Ronaldo','2d','ok','R$ 45k',NULL,NULL,NULL,NULL),
('compras','recebido','Alexandre Assumpcao','ID 1095 — Carvalho Europeu Natural · Insumos OK 17/02/26','Alexandre Assumpcao','Ronaldo','OK','ok',NULL,NULL,NULL,NULL,NULL),
('compras','recebido','Casa Florais — Carvalho Europeu','ID 2283 — 180m3 Carvalho + ferragens 25 portas · Recebido','Casa Florais','Ronaldo','OK','ok',NULL,NULL,NULL,NULL,NULL),

-- ═══ PRODUCAO ═══
('producao','a-iniciar','Silvia Alarico Neves','ID 1807 — 3 Portas Pivotantes · Madeira PENDENTE','Silvia Alarico Neves','Germano','—','warning',NULL,NULL,ARRAY['pendente madeira'],NULL,NULL),
('producao','a-iniciar','Ana Cristina Garcia','ID 2307 — 10 Portas Pivotantes Nogueira · Eq: Clederson/Jean','Ana Cristina Garcia','Clederson/Jean','10d','ok',NULL,'alta',NULL,NULL,NULL),
('producao','a-iniciar','Claudio Mohn Franca','ID 2272 — 48.6m2 Painel + 45m2 Brises + 46 Portas Peroba Laca · Eq: Paulo','Claudio Mohn Franca','Paulo','20d','ok',NULL,'alta',NULL,NULL,NULL),
('producao','a-iniciar','Robinho e Mariana','ID 2254 — 5 Portas · Novo Rumo','Robinho e Mariana','Germano','8d','ok',NULL,NULL,NULL,NULL,NULL),
('producao','checklist','Alexandre Assumpcao','ID 1095 — 4 Portas Carvalho Europeu Natural · Insumos OK · Eq: Ramon','Alexandre Assumpcao','Ramon','3d','ok',NULL,NULL,NULL,NULL,NULL),
('producao','checklist','Henrique de Menezes','ID 221 — Paineis Hall + Porta + Forro Carvalho · Eq: Gilvan','Henrique de Menezes','Gilvan','5d','ok',NULL,NULL,NULL,NULL,NULL),
('producao','checklist','Amanda Rosales','ID 2310 — Lamina Carvalho Mont Blanc Nevado · Eq: Will','Amanda Rosales','Will','4d','ok',NULL,NULL,NULL,NULL,NULL),
('producao','checklist','Bernardo Coutinho','ID 1125 — 10 Portas Pivotantes Carvalho Europeu · Eq: Will/Marcos','Bernardo Coutinho','Will/Marcos','5d','ok',NULL,NULL,NULL,NULL,NULL),
('producao','checklist','Cibele Hasmann','ID 2242/2341 — Marcenaria Formica','Cibele Hasmann','Germano','3d','ok',NULL,NULL,NULL,NULL,NULL),
('producao','checklist','Eduardo Grunebaum','ID 2240 — 4.14 Cortineiro + 7 Mulsanca · BLOQUEADO: cliente indisponivel','Eduardo Grunebaum','Germano','VENCIDO','expired',NULL,NULL,ARRAY['bloqueado'],NULL,NULL),
('producao','checklist','Luana Bastos de Oliveira','ID 1341 — 12 Portas + 23m3 Painel Tauari + Cortineiro + Bancos','Luana Bastos','Germano','8d','ok',NULL,NULL,NULL,NULL,NULL),
('producao','checklist','Rafaela Di Mais','ID 2347 — 1 Porta Pivotante + 1 Bancada + 1 Portico','Rafaela Di Mais','Germano','4d','ok',NULL,NULL,NULL,NULL,NULL),
('producao','checklist','Andre Gurgel','ID 2355/2356 — Rev. Guarda-corpo Carvalho · Eq: Anderson/Clederson/Jean/Ramon','Andre Gurgel','Anderson','5d','ok',NULL,NULL,ARRAY['SP'],NULL,NULL),
('producao','em-producao','Casa Florais — Reinaldo Morais','ID 2283 — 180m3 Carvalho + 21 Portas Piv + 4 Correr · Eq: Higor','Casa Florais','Higor','12d','ok',NULL,NULL,ARRAY['BSB/MT'],65,NULL),
('producao','em-producao','Fazenda Santa Eliza','ID 2308 — Brise + 15 Portas Piv + Correr · Carvalho Smoked · Eq: Marcos','Fazenda Santa Eliza','Marcos','15d','ok',NULL,NULL,ARRAY['SP'],45,NULL),
('producao','em-producao','Inacio Passos Pereira','ID 2265 — 56m2 Lamina Tauari Forro/Painel + 1 Porta · Eq: Marcos','Inacio Passos Pereira','Marcos','8d','ok',NULL,NULL,NULL,55,NULL),
('producao','em-producao','Maria e Mel','ID 1566 — 3 Camarao + 10 Piv + 6 Correr + 207m2 Painel · Eq: Kamin/Clederson','Maria e Mel','Kamin/Clederson','10d','ok',NULL,NULL,ARRAY['MG'],60,NULL),
('producao','em-producao','Paulo Gontijo Junior','ID 1507/2120 — Fechadura + Paineis Cozinha + Closet + Reguas · Eq: Clederson/Will','Paulo Gontijo Junior','Clederson/Will','5d','ok',NULL,NULL,NULL,78,NULL),
('producao','em-producao','Pedro Paulo Meireles Ramos','ID 2277 — 3639m Painel + Brises + 14 Portas Correr · Eq: Cleiton','Pedro Paulo Meireles Ramos','Cleiton','20d','warning',NULL,NULL,ARRAY['BSB'],40,NULL),
('producao','em-producao','Trocha Family — Solarius','ID 1312 — 726m2 Painel Cabreuva + 130m Brise + 27 Portas Piv · Eq: Marivaldo','Trocha Family','Marivaldo','30d','ok',NULL,'alta',ARRAY['Alemanha'],25,NULL),

-- ═══ LOGISTICA ═══
('logistica','pronto','Paulo Gontijo Junior','ID 1507 — Fechadura + Paineis + Closet + Reguas · Aguardando QC','Paulo Gontijo Junior','Ailton','2d','ok',NULL,NULL,ARRAY['CWB→SP'],NULL,NULL),
('logistica','pronto','Inacio Passos Pereira','ID 2265 — 56m2 Tauari Forro/Painel + 1 Porta · Para SP','Inacio Passos Pereira','Ailton','1d','ok',NULL,NULL,NULL,NULL,NULL),
('logistica','separacao','Bernardo Coutinho — RJ','ID 1125 — 10 Portas Pivotantes Carvalho · Conferindo kit','Bernardo Coutinho','Ailton','3d','ok',NULL,NULL,ARRAY['CWB→RJ'],NULL,NULL),
('logistica','separacao','Fazenda Santa Eliza','ID 2308 — Brise + Portas Carvalho Smoked · Parcial','Fazenda Santa Eliza','Ailton','5d','ok',NULL,NULL,ARRAY['CWB→SP'],NULL,NULL),
('logistica','carregamento','Maria e Mel — Nova Lima','ID 1566 — Marcenaria parcial + material piso/forro/deck','Maria e Mel','Ailton','hoje','ok',NULL,NULL,ARRAY['CWB→MG'],NULL,NULL),
('logistica','transito','Casa Florais → Cuiaba','ID 2283 — Forro Lamina · ETA 2 dias','Casa Florais','Motorista','2d','ok',NULL,NULL,ARRAY['CWB→MT'],NULL,NULL),
('logistica','transito','Jorbel → Paraguay','Piso + Forro + Deck · DOCUMENTACAO PENDENTE','Jorbel','Ailton','VENCIDO','expired',NULL,'alta',ARRAY['PY','internacional'],NULL,NULL),
('logistica','entregue','Pedro Campos — Brasilia','Material Beiral + Aditivo Cavas · Entregue','Pedro Campos','Ailton','OK','ok',NULL,NULL,NULL,NULL,NULL),
('logistica','entregue','Aurea Itaim — SP','Portas + Escada + material marcenaria · Entregue','Aurea Itaim','Ailton','OK','ok',NULL,NULL,NULL,NULL,NULL),

-- ═══ OBRAS ═══
('obras','mobilizacao','Luana Bastos — RJ','Forro · Eq: Regis (3) · Fiscal: Davi · Aguardando material','Luana Bastos','Dany','5d','ok',NULL,NULL,ARRAY['RJ'],NULL,NULL),
('obras','mobilizacao','Ruben Feffer — Guaruja','Deck · Eq: Vagner e Rafael · Fiscal: Vagner · Aguardando','Ruben Feffer','Dany','7d','ok',NULL,NULL,ARRAY['SP'],NULL,NULL),
('obras','mobilizacao','Andre Gurgel — SP','Forro 5o Andar · Fiscal: Cristiano · Sem equipe definida · Fim: 13/02','Andre Gurgel','Dany','3d','warning',NULL,NULL,ARRAY['SP'],NULL,NULL),
('obras','mobilizacao','Valter e Renata — SP','Forro · Fiscal: Davi · Sem equipe definida','Valter e Renata','Dany','5d','warning',NULL,NULL,ARRAY['SP'],NULL,NULL),
('obras','mobilizacao','Bruno Lima — Salvador','Reparo Deck · Fiscal: Reinaldo · Aguardando material · Fim: 13/03','Bruno Lima','Dany','10d','ok',NULL,NULL,ARRAY['BA'],NULL,NULL),
('obras','execucao','Pedro Campos — Brasilia','Beiral + Aditivo + Deck + Rooftop · Eq: Jailton/Igor + Carlos/Ray + Rodney · Fiscal: Reinaldo','Pedro Campos','Eq. Brasilia','Fim: 13/02','ok',NULL,'alta',ARRAY['BSB'],72,NULL),
('obras','execucao','Maria e Mel — Nova Lima','Marcenaria + Piso Forro/Deck · Eq: Viny/Wilson + Ramon/Kaique + Geomario · Fiscal: Davi','Maria e Mel','Eq. MG','Fim: 20/02','ok',NULL,'alta',ARRAY['MG'],65,NULL),
('obras','execucao','Aurea Itaim — SP','Portas + Escada + Marcenaria · Eq: Emerson/Atila + Geadson/Walisson + Anderson/Bruno','Aurea Itaim','Eq. SP','—','ok',NULL,NULL,ARRAY['SP'],55,NULL),
('obras','execucao','Felipe Almeida — Baronesa','Pergolado + Forro Projeto · Eq: Alan (2) + Bedeu (5) · Fiscal: Alvaro · Fim: 06/03','Felipe Almeida','Eq. Baronesa','Fim: 06/03','ok',NULL,'alta',ARRAY['SP'],35,NULL),
('obras','execucao','Casa Florais — Cuiaba/BSB','Forro Lamina + Piso · Eq: Eduardo/Lucid + Lucas + David + Reinaldo 3 · Fim: 20/02','Casa Florais','Eq. MT/BSB','Fim: 20/02','ok',NULL,NULL,ARRAY['MT','BSB'],50,NULL),
('obras','execucao','Thiago Miranda — SP','Revestimento Suite · Eq: Isaque · Fiscal: Alvaro · Fim: 13/03','Thiago Miranda','Isaque','Fim: 13/03','ok',NULL,NULL,ARRAY['SP'],30,NULL),
('obras','execucao','Rubens Fugisack — SP','Instalacao Piso · Eq: Diego Jaison · Fiscal: Cristiano','Rubens Fugisack','Diego Jaison','—','ok',NULL,NULL,ARRAY['SP'],25,NULL),
('obras','execucao','Bernardo Coutinho — RJ','Forro · Eq: Geraldo (3) · Fiscal: Davi · Fim: 27/03','Bernardo Coutinho','Geraldo','Fim: 27/03','ok',NULL,NULL,ARRAY['RJ'],20,NULL),
('obras','execucao','Bradesco Irece/Salvador','Instalacao Taco · Eq: Dany (3) · Fim: 27/03 · DIARIO','Bradesco Irece','Dany (3)','Fim: 27/03','ok',NULL,NULL,ARRAY['BA'],30,NULL),
('obras','execucao','Jorbel — Paraguay','Piso-Forro e Deck · Eq: Ademir 4 · Fiscal: Reinaldo · Fim: 30/04','Jorbel','Ademir 4','Fim: 30/04','ok',NULL,'alta',ARRAY['PY'],15,NULL),
('obras','execucao','Ilka — Brasilia','Estrutura · Eq: Reinaldo 3 · Fiscal: Reinaldo · Fim: 20/03','Ilka','Reinaldo 3','Fim: 20/03','ok',NULL,NULL,ARRAY['BSB'],30,NULL),
('obras','execucao','Elson — SP','Forro · Eq: Rogerio · Fiscal: Alvaro','Elson','Rogerio','—','ok',NULL,NULL,ARRAY['SP'],40,NULL),
('obras','execucao','Ricardo Ernesto — Porto Alegre','Reparo Piso · Eq: Carlao/Jocevanio · Fiscal: Carlos','Ricardo Ernesto','Carlao','—','ok',NULL,NULL,ARRAY['RS'],40,NULL),
('obras','execucao','Pedro Ramos — Brasilia','Estrutura de Forro · Eq: Reinaldo 2 · Fiscal: Reinaldo','Pedro Ramos','Reinaldo 2','—','ok',NULL,NULL,ARRAY['BSB'],10,NULL),
('obras','travado','Rafaela Dimasi — SP','Forro · Eq: TRAVADO · Fiscal: Cristiano','Rafaela Dimasi','TRAVADO','BLOQUEADO','expired',NULL,NULL,ARRAY['SP','bloqueado'],NULL,NULL),
('obras','travado','Gabriel Lacher — Brasilia','Piso e Painel · Eq: TRAVADO · Fiscal: Reinaldo · Fim: 13/03','Gabriel Lacher','TRAVADO','BLOQUEADO','expired',NULL,NULL,ARRAY['BSB','bloqueado'],NULL,NULL),
('obras','travado','Ana Cristina — Jatai GO','Revestimento Forro · Eq: TRAVADO · Fiscal: Reinaldo · Fim: 13/03','Ana Cristina','TRAVADO','BLOQUEADO','expired',NULL,NULL,ARRAY['GO','bloqueado'],NULL,NULL),
('obras','travado','Fernando e Maraisa — Goiania','Estrutura Painel · Eq: Reinaldo 2 · Fiscal: Reinaldo · TRAVADO','Fernando e Maraisa','Reinaldo 2','BLOQUEADO','expired',NULL,NULL,ARRAY['GO','bloqueado'],NULL,NULL),
('obras','reparos','Priscila Dear — Riviera/SP','Reparo-Bandeira + Acabamento · Eq: Anderson/Bruno + Luiz/Lourival','Priscila Dear','Eq. SP','5d','ok',NULL,NULL,ARRAY['SP'],40,NULL),
('obras','reparos','Leandro Silva — SP/Riviera','Acabamento + Rodateto · Eq: Luiz/Lourival + Fernando/Silvio','Leandro Silva','Eq. SP','3d','ok',NULL,NULL,ARRAY['SP'],85,NULL),
('obras','reparos','Luiz Andre — Guaruja/SP','Acabamento + Reparo Piso + Raspagem Deck · Eq: Vanderson/Kauan/Sidney + Alexandre/Rafael','Luiz Andre','Eq. SP','7d','ok',NULL,NULL,ARRAY['SP'],60,NULL),
('obras','reparos','Davidson — SP','Remocao Forro · Eq: Vagner e Rafael · Fiscal: Vagner','Davidson','Vagner/Rafael','2d','ok',NULL,NULL,ARRAY['SP'],70,NULL),
('obras','reparos','Maristela — SP','Acabamento Escada · Eq: Vagner e Rafael · Fiscal: Vagner','Maristela','Vagner/Rafael','3d','ok',NULL,NULL,ARRAY['SP'],50,NULL),
('obras','finalizado','Fernando Aragon — SP','Acabamento · Eq: Vanderson/Kauan/Sidney · Fiscal: Alvaro · Finalizado: 17/02','Fernando Aragon','Eq. SP','OK','ok',NULL,NULL,ARRAY['SP'],100,NULL),
('obras','finalizado','Rosana Braido — SP','Acabamento · Eq: Vanderson/Kauan/Sidney · Fiscal: Alvaro · Finalizado: 17/02','Rosana Braido','Eq. SP','OK','ok',NULL,NULL,ARRAY['SP'],100,NULL),
('obras','finalizado','Ricardo Fanin — SP','Piso · Eq: Henrique-Dany (2) · Fiscal: Cristiano · Finalizado: 13/02','Ricardo Fanin','Eq. SP','OK','ok',NULL,NULL,ARRAY['SP'],100,NULL),
('obras','finalizado','Roberto Bloes — SP','Forro · Eq: Ismael · Fiscal: Davi · Finalizado: 24/02','Roberto Bloes','Ismael','OK','ok',NULL,NULL,ARRAY['SP'],100,NULL),

-- ═══ FINANCEIRO ═══
('financeiro','contrato','Claudio Mohn Franca','R$ 420k — 48.6m2 Painel + 46 Portas Peroba Laca','Claudio Mohn Franca','Karla','5d','ok','R$ 420k',NULL,NULL,NULL,NULL),
('financeiro','contrato','Trocha Family — Solarius','R$ 850k — 726m2 Painel + 27 Portas · Projeto internacional','Trocha Family','Karla','10d','warning','R$ 850k','alta',NULL,NULL,NULL),
('financeiro','medicao','Pedro Campos — Brasilia','Medicao 3/4 — 72% concluido · Beiral + Deck','Pedro Campos','Natalia','5d','ok','R$ 95k',NULL,NULL,NULL,NULL),
('financeiro','medicao','Maria e Mel — Nova Lima','Medicao 2/3 — 65% · Marcenaria + Piso + Deck','Maria e Mel','Natalia','5d','ok','R$ 85k',NULL,NULL,NULL,NULL),
('financeiro','medicao','Felipe Almeida — Baronesa','Medicao 1/3 — 35% · Pergolado + Forro','Felipe Almeida','Natalia','3d','ok','R$ 110k',NULL,NULL,NULL,NULL),
('financeiro','faturamento','Jorbel — Paraguay','NF Internacional — R$ 130k 1a parcela · Docs PY pendentes','Jorbel','Karla','3d','warning','R$ 130k',NULL,NULL,NULL,NULL),
('financeiro','faturamento','Casa Florais','NF Parcial — R$ 78k Forro + Piso','Casa Florais','Karla','2d','ok','R$ 78k',NULL,NULL,NULL,NULL),
('financeiro','cobranca','Aurea Itaim — SP','Parcela 2 atrasada 15 dias — R$ 65k','Aurea Itaim','Karla','VENCIDO','expired','R$ 65k',NULL,NULL,NULL,NULL),
('financeiro','recebido','Ricardo Fanin — SP','Medicao final R$ 125k · Obra concluida 13/02','Ricardo Fanin','Karla','OK','ok','R$ 125k',NULL,NULL,NULL,NULL),
('financeiro','recebido','Fernando Aragon — SP','Pagamento final R$ 155k · Obra concluida 17/02','Fernando Aragon','Karla','OK','ok','R$ 155k',NULL,NULL,NULL,NULL),

-- ═══ ATENDIMENTO ═══
('atendimento','onboarding','Claudio Mohn Franca','R$ 420k — Criar grupo + pasta + boas-vindas — projeto novo','Claudio Mohn Franca','Talita','D+2','ok',NULL,NULL,NULL,NULL,NULL),
('atendimento','onboarding','Trocha Family — Solarius','R$ 850k — Cliente internacional — onboarding especial','Trocha Family','Talita','D+3','ok',NULL,'alta',ARRAY['internacional'],NULL,NULL),
('atendimento','acompanhamento','Pedro Campos — BSB','⚠️ Cliente cobrando — obra paralisada — comunicar situacao','Pedro Campos','Talita','URGENTE','expired',NULL,NULL,ARRAY['risco','BSB'],NULL,NULL),
('atendimento','acompanhamento','Maria e Mel — Nova Lima','65% concluido — proximo update sexta · Fiscal: Davi','Maria e Mel','Talita','3d','ok',NULL,NULL,ARRAY['MG'],NULL,NULL),
('atendimento','acompanhamento','Felipe Almeida — Baronesa','35% — pergolado + forro — atualizacao semanal','Felipe Almeida','Talita','semanal','ok',NULL,NULL,NULL,NULL,NULL),
('atendimento','acompanhamento','Jorbel — Paraguay','15% — projeto internacional — comunicacao bilingual','Jorbel','Talita','semanal','ok',NULL,NULL,ARRAY['PY'],NULL,NULL),
('atendimento','acompanhamento','Aurea Itaim — SP','55% — portas + escada + marcenaria','Aurea Itaim','Talita','3d','ok',NULL,NULL,NULL,NULL,NULL),
('atendimento','entrega-formal','Fernando Aragon — SP','Finalizado 17/02 — agendar entrega formal + fotos','Fernando Aragon','Talita','2d','ok',NULL,NULL,NULL,NULL,NULL),
('atendimento','entrega-formal','Rosana Braido — SP','Finalizado 17/02 — entrega formal + NPS','Rosana Braido','Talita','2d','ok',NULL,NULL,NULL,NULL,NULL),
('atendimento','entrega-formal','Ricardo Fanin — SP','Finalizado 13/02 — Piso · NPS coletado: 9.5','Ricardo Fanin','Talita','OK','ok',NULL,NULL,NULL,NULL,NULL),
('atendimento','pos-venda','Roberto Bloes — SP','Forro finalizado 24/02 — NPS pendente','Roberto Bloes','Talita','VENCIDO','expired',NULL,NULL,ARRAY['nps'],NULL,NULL),

-- ═══ FISCAL ═══
('fiscal','agendada','Ana Cristina — Jatai GO','Revestimento Forro · Fiscal: REINALDO · Fim: 13/03','Ana Cristina','Reinaldo','5d','ok',NULL,NULL,ARRAY['GO','liberacao'],NULL,NULL),
('fiscal','agendada','Thiago Miranda — SP','Vistoria suite · Fiscal: ALVARO · Revestimento 30%','Thiago Miranda','Alvaro','3d','ok',NULL,NULL,ARRAY['SP'],NULL,NULL),
('fiscal','agendada','Bernardo Coutinho — RJ','Vistoria forro · Fiscal: DAVI · Fim: 27/03','Bernardo Coutinho','Davi','5d','ok',NULL,NULL,ARRAY['RJ'],NULL,NULL),
('fiscal','em-campo','Pedro Campos — BSB','Fiscal: REINALDO · Beiral + Deck + Rooftop · 72%','Pedro Campos','Reinaldo','acomp.','ok',NULL,NULL,ARRAY['BSB'],NULL,NULL),
('fiscal','em-campo','Maria e Mel — Nova Lima','Fiscal: DAVI · Piso Forro/Deck · 65%','Maria e Mel','Davi','acomp.','ok',NULL,NULL,ARRAY['MG'],NULL,NULL),
('fiscal','em-campo','Felipe Almeida — Baronesa','Fiscal: ALVARO · Pergolado + Forro · 35% · DIARIO','Felipe Almeida','Alvaro','acomp.','ok',NULL,NULL,ARRAY['SP'],NULL,NULL),
('fiscal','em-campo','Jorbel — Paraguay','Fiscal: REINALDO · Piso-Forro-Deck · 15%','Jorbel','Reinaldo','acomp.','ok',NULL,NULL,ARRAY['PY'],NULL,NULL),
('fiscal','em-campo','Luiz Andre — Guaruja/SP','Fiscal: ALVARO · Acabamento + Reparos · 60%','Luiz Andre','Alvaro','acomp.','ok',NULL,NULL,ARRAY['SP'],NULL,NULL),
('fiscal','em-campo','Rubens Fugisack — SP','Fiscal: CRISTIANO · Instalacao Piso · 25%','Rubens Fugisack','Cristiano','acomp.','ok',NULL,NULL,ARRAY['SP'],NULL,NULL),
('fiscal','relatorio','Casa Florais — Cuiaba/BSB','Fiscal: REINALDO · Forro + Piso · Relatorio vistoria parcial','Casa Florais','Reinaldo','2d','ok',NULL,NULL,NULL,NULL,NULL),
('fiscal','liberada','Aurea Itaim — SP','Liberacao parcial · Portas + Escada + Marcenaria','Aurea Itaim','Alvaro','OK','ok',NULL,NULL,NULL,NULL,3),
('fiscal','liberada','Bradesco Irece — BA','Liberado para instalacao taco','Bradesco Irece','Reinaldo','OK','ok',NULL,NULL,NULL,NULL,3),
('fiscal','bloqueada','Rafaela Dimasi — SP','Fiscal: CRISTIANO · Forro TRAVADO — nao agendar vistoria','Rafaela Dimasi','Cristiano','BLOQUEADO','expired',NULL,NULL,ARRAY['bloqueado'],NULL,NULL),
('fiscal','bloqueada','Gabriel Lacher — BSB','Fiscal: REINALDO · Piso + Painel TRAVADO','Gabriel Lacher','Reinaldo','BLOQUEADO','expired',NULL,NULL,ARRAY['bloqueado'],NULL,NULL),

-- ═══ PMO (produtividade) ═══
('produtividade','pre-crono','Claudio Mohn Franca','Estimativa: 45 dias uteis — 48.6m2 + 46 portas','Claudio Mohn Franca','Natalia','3d','ok',NULL,'alta',NULL,NULL,NULL),
('produtividade','pre-crono','Trocha Family — Solarius','Estimativa: 60 dias — 726m2 + 27 portas · Projeto maior','Trocha Family','Natalia','5d','ok',NULL,'alta',NULL,NULL,NULL),
('produtividade','ativo','Pedro Campos — BSB','72% · Beiral + Deck · PARALISADA — produtividade 0 ha 10d','Pedro Campos','Natalia','—','expired',NULL,NULL,NULL,72,NULL),
('produtividade','ativo','Maria e Mel — Nova Lima','65% · Piso Forro/Deck · Produtividade boa — Fim: 20/02','Maria e Mel','Natalia','Fim: 20/02','ok',NULL,NULL,NULL,65,NULL),
('produtividade','ativo','Felipe Almeida — Baronesa','35% · Pergolado + Forro · DIARIO · Fim: 06/03','Felipe Almeida','Natalia','Fim: 06/03','ok',NULL,NULL,NULL,35,NULL),
('produtividade','ativo','Jorbel — Paraguay','15% · Piso-Forro-Deck · Fim: 30/04 · Projeto longo','Jorbel','Natalia','Fim: 30/04','ok',NULL,NULL,NULL,15,NULL),
('produtividade','ativo','Aurea Itaim — SP','55% · Portas + Escada · No prazo','Aurea Itaim','Natalia','—','ok',NULL,NULL,NULL,55,NULL),
('produtividade','ativo','Bernardo Coutinho — RJ','20% · Forro · Eq: Geraldo (3) · Fim: 27/03','Bernardo Coutinho','Natalia','Fim: 27/03','ok',NULL,NULL,NULL,20,NULL),
('produtividade','pagamento','Leandro Silva — SP/Riviera','85% · Acabamento + Rodateto · Retencao R$ 8k','Leandro Silva','Natalia','D15','ok','R$ 8k',NULL,NULL,NULL,NULL),
('produtividade','pagamento','Luiz Andre — Guaruja/SP','60% · Reparos · Retencao R$ 12k','Luiz Andre','Natalia','D15','ok','R$ 12k',NULL,NULL,NULL,NULL),
('produtividade','aceite','Fernando Aragon — SP','Finalizado 17/02 — termo aceite PENDENTE','Fernando Aragon','Natalia','VENCIDO','expired',NULL,NULL,NULL,NULL,NULL),
('produtividade','aceite','Rosana Braido — SP','Finalizado 17/02 — termo aceite PENDENTE','Rosana Braido','Natalia','VENCIDO','expired',NULL,NULL,NULL,NULL,NULL),
('produtividade','aceite','Ricardo Fanin — SP','Finalizado 13/02 — termo aceite PENDENTE','Ricardo Fanin','Natalia','VENCIDO','expired',NULL,NULL,NULL,NULL,NULL),
('produtividade','encerrado','Roberto Bloes — SP','Forro finalizado 24/02 · Aceite + pagamento OK','Roberto Bloes','Natalia','OK','ok',NULL,NULL,NULL,NULL,NULL),

-- ═══ RH ═══
('rh','vaga','2o Fiscal BSB/GO','Reinaldo com 12 obras — urgente contratar fiscal reforco Brasilia/Goias',NULL,'Talicia','5d','expired',NULL,'alta',NULL,NULL,NULL),
('rh','vaga','Instalador Piso — SP','2 vagas — reforco para obras SP (Aurea Itaim + Thiago Miranda)',NULL,'Talicia','10d','ok',NULL,NULL,NULL,NULL,NULL),
('rh','vaga','Marceneiro CNC — Fabrica','Producao a 88% capacidade — precisa operador CNC',NULL,'Talicia','15d','ok',NULL,NULL,NULL,NULL,NULL),
('rh','alocacao','Vanderson/Kauan/Sidney','DISPONIVEL — finalizaram Aragon + Braido · Realocar p/ proxima obra SP',NULL,'Dany','2d','ok',NULL,NULL,ARRAY['SP'],NULL,NULL),
('rh','alocacao','Eq. Henrique-Dany (2)','DISPONIVEL — finalizou Ricardo Fanin · Realocar',NULL,'Dany','2d','ok',NULL,NULL,ARRAY['SP'],NULL,NULL),
('rh','alocacao','Ismael','DISPONIVEL — finalizou Roberto Bloes · Realocar p/ forro SP',NULL,'Dany','3d','ok',NULL,NULL,ARRAY['SP'],NULL,NULL),
('rh','producao-equipes','Higor — Casa Florais','180m3 Carvalho + 25 Portas · Producao desde 27/10 · 65%','Casa Florais','Germano','15d','ok',NULL,NULL,NULL,NULL,NULL),
('rh','producao-equipes','Marcos — Santa Eliza + Inacio','Brise + Portas + Forro · 2 obras simultaneas',NULL,'Germano','15d','ok',NULL,NULL,NULL,NULL,NULL),
('rh','producao-equipes','Marivaldo — Trocha Family','726m2 Painel Cabreuva + 130m Brise + 27 Portas · Projeto longo','Trocha Family','Germano','30d','ok',NULL,'alta',NULL,NULL,NULL),
('rh','producao-equipes','Cleiton — Pedro Paulo Ramos','3639m Painel + Brises + 14 Portas · Sobrecarregado','Pedro Paulo Ramos','Germano','20d','warning',NULL,NULL,NULL,NULL,NULL),
('rh','internacional','Ademir 4 — Jorbel (Paraguay)','Piso-Forro-Deck · Ate 30/04/26 · Logistica RH internacional','Jorbel','Talicia','60d','ok',NULL,NULL,ARRAY['PY'],NULL,NULL),

-- ═══ ORCAMENTO ═══
('orcamento','solicitacao','Silvia Alarico Neves','ID 1807 — 3 Portas Pivotantes · SEM MADEIRA DEFINIDA','Silvia Alarico Neves','Ranieri','1d','expired',NULL,'alta',ARRAY['incompleto'],NULL,NULL),
('orcamento','solicitacao','Robinho e Mariana','ID 2254 — 5 Portas · Novo Rumo · Aguardando medidas','Robinho e Mariana','Ranieri','2d','ok',NULL,NULL,NULL,NULL,NULL),
('orcamento','solicitacao','GIC Patrimonial','ID 2342 — Pendente definicao fechaduras · TRAVADO','GIC Patrimonial','Ranieri','VENCIDO','expired',NULL,NULL,ARRAY['impedimento'],NULL,NULL),
('orcamento','analise-orc','Mohmed Nazir','ID 1629 — Cortineiro + novo contrato · Analisando escopo','Mohmed Nazir','Ranieri','3d','ok','~R$ 45k',NULL,NULL,NULL,NULL),
('orcamento','analise-orc','Luana Bastos de Oliveira','ID 1341 — 12 Portas + 23m3 Painel Tauari + Cortineiro + Bancos','Luana Bastos','Ranieri','3d','ok','~R$ 150k',NULL,NULL,NULL,NULL),
('orcamento','calculo','Trocha Family — Solarius','ID 1312 — 726m2 Cabreuva + 130m Brise + 27 Portas · Projeto complexo','Trocha Family','Ranieri','5d','warning','~R$ 850k','alta',NULL,NULL,NULL),
('orcamento','calculo','Ana Cristina Garcia','ID 2307 — 10 Portas Pivotantes Nogueira','Ana Cristina Garcia','Ranieri','2d','ok','~R$ 120k',NULL,NULL,NULL,NULL),
('orcamento','proposta-pronta','Claudio Mohn Franca','ID 2272 — R$ 420k · 48.6m2 Painel + 46 Portas Peroba Laca · Aprovada','Claudio Mohn Franca','Ranieri','OK','ok','R$ 420k',NULL,NULL,NULL,NULL),
('orcamento','proposta-pronta','Jorbel — Paraguay','R$ 420k · Piso-Forro-Deck · Contrato assinado','Jorbel','Ranieri','OK','ok','R$ 420k',NULL,NULL,NULL,NULL),
('orcamento','proposta-pronta','Felipe Almeida — Baronesa','R$ 340k · Pergolado + Forro Projeto · Em execucao','Felipe Almeida','Ranieri','OK','ok','R$ 340k',NULL,NULL,NULL,NULL);
